-- insert into poll (poll_id, question) values (1, 'What is your favorite color?');
-- insert into option (option_id, option_value, poll_id) values (1, 'Yellow', 1);
-- insert into option (option_id, option_value, poll_id) values (2, 'Red', 1);
-- insert into option (option_id, option_value, poll_id) values (3, 'Blue', 1);
--
-- insert into poll (poll_id, question) values (2, 'What is your favorite food?');
-- insert into option (option_id, option_value, poll_id) values (4, 'Sushi', 2);
-- insert into option (option_id, option_value, poll_id) values (5, 'Tacos', 2);
-- insert into option (option_id, option_value, poll_id) values (6, 'Fries', 2);
--
-- insert into poll (poll_id, question) values (3, 'What is your favorite season?');
-- insert into option (option_id, option_value, poll_id) values (7, 'Autumn', 3);
-- insert into option (option_id, option_value, poll_id) values (8, 'Spring', 3);
-- insert into option (option_id, option_value, poll_id) values (9, 'Winter', 3);
-- insert into option (option_id, option_value, poll_id) values (10, 'Summer', 3);
--
-- insert into poll (poll_id, question) values (4, 'What is your favorite drink?');
-- insert into option (option_id, option_value, poll_id) values (11, 'Vodka', 4);
-- insert into option (option_id, option_value, poll_id) values (12, 'Rum', 4);
-- insert into option (option_id, option_value, poll_id) values (13, 'Brandy', 4);
--
-- insert into poll (poll_id, question) values (5, 'What is your favorite tree?');
-- insert into option (option_id, option_value, poll_id) values (14, 'Birch', 5);
-- insert into option (option_id, option_value, poll_id) values (15, 'Maple', 5);
-- insert into option (option_id, option_value, poll_id) values (16, 'Oak', 5);
--
-- insert into poll (poll_id, question) values (6, 'What is your favorite movie?');
-- insert into option (option_id, option_value, poll_id) values (17, 'Corpse Bride', 6);
-- insert into option (option_id, option_value, poll_id) values (18, 'Clerks', 6);
-- insert into option (option_id, option_value, poll_id) values (19, 'Fast and Furious', 6);
--
-- insert into poll (poll_id, question) values (7, 'What is your favorite car?');
-- insert into option (option_id, option_value, poll_id) values (20, 'Tesla', 7);
-- insert into option (option_id, option_value, poll_id) values (21, 'Toyota', 7);
-- insert into option (option_id, option_value, poll_id) values (22, 'Honda', 7);
--
-- insert into poll (poll_id, question) values (8, 'What is your favorite candy?');
-- insert into option (option_id, option_value, poll_id) values (23, 'Skittles', 8);
-- insert into option (option_id, option_value, poll_id) values (24, 'Sour Patch', 8);
-- insert into option (option_id, option_value, poll_id) values (25, 'Chocolate', 8);
--
-- insert into poll (poll_id, question) values (9, 'What is your favorite number?');
-- insert into option (option_id, option_value, poll_id) values (26, 'One', 9);
-- insert into option (option_id, option_value, poll_id) values (27, 'Two', 9);
-- insert into option (option_id, option_value, poll_id) values (28, 'Three', 9);
--
-- insert into poll (poll_id, question) values (10, 'What is your favorite animal?');
-- insert into option (option_id, option_value, poll_id) values (29, 'Dog', 10);
-- insert into option (option_id, option_value, poll_id) values (30, 'Cat', 10);
-- insert into option (option_id, option_value, poll_id) values (31, 'Bear', 10);
--
-- insert into poll (poll_id, question) values (11, 'What is your favorite sport?');
-- insert into option (option_id, option_value, poll_id) values (32, 'Cycling', 11);
-- insert into option (option_id, option_value, poll_id) values (33, 'Basketball', 11);
-- insert into option (option_id, option_value, poll_id) values (34, 'Soccer', 11);
--
-- insert into poll (poll_id, question) values (12, 'What is your favorite game?');
-- insert into option (option_id, option_value, poll_id) values (35, 'Final Fantasy', 12);
-- insert into option (option_id, option_value, poll_id) values (36, 'Call of Duty', 12);
-- insert into option (option_id, option_value, poll_id) values (37, 'Skyrim', 12);
--
-- insert into poll (poll_id, question) values (13, 'What is your favorite desert?');
-- insert into option (option_id, option_value, poll_id) values (38, 'Ice cream', 13);
-- insert into option (option_id, option_value, poll_id) values (39, 'Chocolate cake', 13);
-- insert into option (option_id, option_value, poll_id) values (40, 'Mochi', 13);
--
-- insert into poll (poll_id, question) values (14, 'What is your favorite day of the week?');
-- insert into option (option_id, option_value, poll_id) values (41, 'Monday', 14);
-- insert into option (option_id, option_value, poll_id) values (42, 'Tuesday', 14);
-- insert into option (option_id, option_value, poll_id) values (43, 'Wednesday', 14);
-- insert into option (option_id, option_value, poll_id) values (44, 'Thursday', 14);
-- insert into option (option_id, option_value, poll_id) values (45, 'Friday', 14);
-- insert into option (option_id, option_value, poll_id) values (46, 'Saturday', 14);
-- insert into option (option_id, option_value, poll_id) values (47, 'Sunday', 14);
--
-- insert into poll (poll_id, question) values (15, 'What is your favorite instructor?');
-- insert into option (option_id, option_value, poll_id) values (48, 'Froilan', 15);
-- insert into option (option_id, option_value, poll_id) values (49, 'Dolio', 15);
-- insert into option (option_id, option_value, poll_id) values (50, 'Chris', 15);
-- insert into option (option_id, option_value, poll_id) values (51, 'Roberto', 15);
-- insert into option (option_id, option_value, poll_id) values (52, 'Kris', 15);